apiVersion: v1
kind: Service
metadata:
  name: fintech-frontend-service
  namespace: fintech
  labels:
    app: fintech-frontend
spec:
  type: ClusterIP
  selector:
    app: fintech-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

